[package]
name = "datastart"
version = "0.1.0"
edition = "2024"
publish = false


[dependencies]
topcoat = { version="0.5.0", features = ["datastar"] }
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros"] }
datastar = "0.3.1"
futures-core = "0.3.34"
futures-util = "0.3.34"

[lints]
